[[redirects]]
  from = "https://www.sanctumwellbeing.co.uk"
  to = "https://sanctumwellbeing.co.uk"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
